import { IonBackButton, IonButtons, IonContent, IonHeader, IonPage, IonTitle, IonToolbar } from '@ionic/react';
import { useTranslation } from 'react-i18next';
import { useSettingsStore } from '../stores/useSettingsStore';
import './Privacy.css';

const CONTACT_EMAIL = 'contact@bleriotnoguia.com';
const LAST_UPDATED = new Date(2026, 8, 26);

type Section = { title: string; paragraphs: string[] };

const CONTENT: Record<string, { intro: string; sections: Section[] }> = {
  fr: {
    intro:
      "Biquiz est un quiz biblique gratuit, sans compte, sans publicité. Cette page explique quelles données l'application utilise et pourquoi.",
    sections: [
      {
        title: 'Données enregistrées sur votre appareil',
        paragraphs: [
          'Votre progression (étoiles), vos dernières réponses par thème et vos réglages sont enregistrés uniquement sur votre appareil. Ils ne sont pas envoyés sur nos serveurs.',
          'Vous pouvez les effacer à tout moment depuis Paramètres › Réinitialiser ma progression, ou en désinstallant l’application.',
        ],
      },
      {
        title: "Statistiques d'utilisation",
        paragraphs: [
          "Pour améliorer l'application et ses questions, Biquiz envoie des statistiques d'utilisation : ouverture de l'application, pages consultées, début et fin d'un quiz (thème et nombre de bonnes réponses), langue et type d'appareil (Android ou web).",
          "Ces statistiques sont associées à un identifiant aléatoire généré par l'application. Il ne permet pas de vous identifier : nous ne collectons ni nom, ni adresse e-mail, ni localisation, ni contacts.",
        ],
      },
      {
        title: 'Signalement de questions',
        paragraphs: [
          "Lorsque vous signalez une erreur dans une question, nous recevons la question concernée, le motif choisi, votre commentaire facultatif, la langue et l'identifiant aléatoire de l'appareil (pour limiter les abus).",
        ],
      },
      {
        title: 'E-mails',
        paragraphs: [
          'Si vous nous écrivez (contact ou suggestion de question), votre adresse e-mail sert uniquement à vous répondre.',
        ],
      },
      {
        title: 'Notifications',
        paragraphs: [
          "Le rappel quotidien est programmé directement sur votre appareil. Aucune donnée n'est envoyée pour cela, et vous pouvez le désactiver dans les paramètres.",
        ],
      },
      {
        title: 'Hébergement et partage',
        paragraphs: [
          "Les questions, les statistiques et les signalements sont hébergés par Supabase. Ces données ne sont ni vendues, ni partagées avec des tiers à des fins publicitaires.",
        ],
      },
      {
        title: 'Vos droits',
        paragraphs: [
          `Pour toute question ou pour demander la suppression de vos données, écrivez-nous à ${CONTACT_EMAIL}.`,
        ],
      },
    ],
  },
  en: {
    intro:
      'Biquiz is a free Bible quiz with no account and no ads. This page explains which data the app uses and why.',
    sections: [
      {
        title: 'Data stored on your device',
        paragraphs: [
          'Your progress (stars), your latest answers per theme and your settings are stored only on your device. They are not sent to our servers.',
          'You can erase them at any time from Settings › Reset my progress, or by uninstalling the app.',
        ],
      },
      {
        title: 'Usage statistics',
        paragraphs: [
          'To improve the app and its questions, Biquiz sends usage statistics: app launches, pages viewed, quiz start and completion (theme and number of correct answers), language and device type (Android or web).',
          'These statistics are tied to a random identifier generated by the app. It cannot identify you: we do not collect your name, email address, location or contacts.',
        ],
      },
      {
        title: 'Question reports',
        paragraphs: [
          'When you report a mistake in a question, we receive the question, the selected reason, your optional comment, the language and the random device identifier (to prevent abuse).',
        ],
      },
      {
        title: 'Emails',
        paragraphs: ['If you write to us (contact or question suggestion), your email address is only used to reply to you.'],
      },
      {
        title: 'Notifications',
        paragraphs: [
          'The daily reminder is scheduled directly on your device. No data is sent for it, and you can turn it off in the settings.',
        ],
      },
      {
        title: 'Hosting and sharing',
        paragraphs: [
          'Questions, statistics and reports are hosted by Supabase. This data is never sold or shared with third parties for advertising.',
        ],
      },
      {
        title: 'Your rights',
        paragraphs: [`For any question or to request the deletion of your data, write to us at ${CONTACT_EMAIL}.`],
      },
    ],
  },
};

const Privacy: React.FC = () => {
  const { t } = useTranslation();
  const language = useSettingsStore((s) => s.language);
  const content = CONTENT[language] ?? CONTENT.fr;

  return (
    <IonPage>
      <IonHeader>
        <IonToolbar color="primary">
          <IonButtons slot="start">
            <IonBackButton defaultHref="/about" />
          </IonButtons>
          <IonTitle>{t('privacyRule')}</IonTitle>
        </IonToolbar>
      </IonHeader>

      <IonContent fullscreen className="ion-padding">
        <div className="privacy">
          <p className="privacy-updated">
            {t('lastUpdated')} {LAST_UPDATED.toLocaleDateString(language, { day: 'numeric', month: 'long', year: 'numeric' })}
          </p>
          <p>{content.intro}</p>
          {content.sections.map((section) => (
            <section key={section.title}>
              <h2>{section.title}</h2>
              {section.paragraphs.map((p) => (
                <p key={p}>{p}</p>
              ))}
            </section>
          ))}
        </div>
      </IonContent>
    </IonPage>
  );
};

export default Privacy;
