-- True/false question type, stable theme keys and normalized duplicate detection for imports.

-- ============================================================
-- IDENTITY COLUMNS
-- ============================================================
-- The baseline schema declares plain bigint ids while the hosted project uses identity
-- columns. Align fresh environments; this is a no-op where identity already exists.
DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'question_types',
    'question_type_translations',
    'question_categories',
    'question_category_translations',
    'questions',
    'question_translations',
    'question_options',
    'question_option_translations'
  ] LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = t AND column_name = 'id' AND is_identity = 'NO'
    ) THEN
      EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', t);
      EXECUTE format(
        'SELECT setval(pg_get_serial_sequence(%L, %L), GREATEST((SELECT COALESCE(max(id), 0) FROM public.%I), 1))',
        'public.' || t, 'id', t
      );
    END IF;
  END LOOP;
END $$;

-- ============================================================
-- TRUE / FALSE QUESTION TYPE
-- ============================================================

INSERT INTO public.question_types (id, code)
SELECT COALESCE((SELECT max(id) FROM public.question_types), 0) + 1, 'true_false'
WHERE NOT EXISTS (SELECT 1 FROM public.question_types WHERE code = 'true_false');

INSERT INTO public.question_type_translations (question_type_id, locale, name)
SELECT qt.id, v.locale, v.name
FROM public.question_types qt
CROSS JOIN (VALUES ('en', 'True or false'), ('fr', 'Vrai ou faux')) AS v(locale, name)
WHERE qt.code = 'true_false'
  AND NOT EXISTS (
    SELECT 1 FROM public.question_type_translations x
    WHERE x.question_type_id = qt.id AND x.locale = v.locale
  );

-- ============================================================
-- STABLE THEME KEYS
-- ============================================================
-- Several source themes share a name (e.g. "Vrai ou Faux" for themes 6, 12, 18…), so imports
-- identify themes by an optional key such as "jw-bible-quiz-12".

ALTER TABLE public.question_categories ADD COLUMN IF NOT EXISTS source_key text;

CREATE UNIQUE INDEX IF NOT EXISTS question_categories_source_key_key
  ON public.question_categories (source_key)
  WHERE source_key IS NOT NULL;

CREATE OR REPLACE FUNCTION public.get_categories()
RETURNS jsonb
LANGUAGE sql
STABLE
SET search_path = ''
AS $$
  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'id', c.id,
      'level', c.level,
      'is_active', c.is_active,
      'created_at', c.created_at,
      'source_key', c.source_key,
      'translate', (
        SELECT jsonb_agg(jsonb_build_object('locale', t.locale, 'name', t.name))
        FROM public.question_category_translations t
        WHERE t.question_category_id = c.id
      )
    )
    ORDER BY c.level, c.id
  ), '[]'::jsonb)
  FROM public.question_categories c;
$$;

-- ============================================================
-- TEXT NORMALIZATION (duplicate detection)
-- ============================================================
-- Mirrors normalizeText() in apps/biquiz-admin/src/modules/admin/import/parseImport.ts.

CREATE OR REPLACE FUNCTION public.normalize_text(p_text text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
SET search_path = ''
AS $f$
  SELECT btrim(
    regexp_replace(
      regexp_replace(
        regexp_replace(
          translate(
            lower(COALESCE(p_text, '')),
            '’‘ʼ`´“”„«»' || chr(160) || chr(8239) || chr(8201),
            $q$'''''"""""   $q$
          ),
          '\s*"\s*', '"', 'g'
        ),
        '\s+([?!:;.,])', '\1', 'g'
      ),
      '\s+', ' ', 'g'
    )
  );
$f$;

-- ============================================================
-- IMPORT
-- ============================================================
-- Payload: { "themes": [ { "category_id"?, "key"?, "name_fr", "name_en"?, "level"?,
--   "questions": [ { "type"?, "name_fr", "name_en"?, "source_text_fr"?, "source_text_en"?,
--     "options": [ { "name_fr", "name_en"?, "is_correct" } ] } ] } ] }
-- Theme resolution: category_id, else key, else name. With a key, the name fallback only
-- considers categories without a key (and assigns the key), so same-named themes stay apart.
-- "type" is "multiple_choice_single_answer" or "true_false"; when absent, a question whose
-- two options are Vrai/Faux (or True/False) is typed true_false.

CREATE OR REPLACE FUNCTION public.import_questions(p_payload jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SET search_path = ''
AS $$
DECLARE
  v_theme jsonb;
  v_question jsonb;
  v_options jsonb;
  v_category_id bigint;
  v_key text;
  v_theme_fr text;
  v_theme_en text;
  v_theme_label text;
  v_q_fr text;
  v_q_en text;
  v_source_fr text;
  v_type_code text;
  v_type_id bigint;
  v_labels text[];
  v_correct integer;
  v_theme_idx integer := 0;
  v_q_idx integer;
  v_categories_created integer := 0;
  v_inserted integer := 0;
  v_skipped integer := 0;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Admin privileges required' USING ERRCODE = '42501';
  END IF;

  IF jsonb_typeof(p_payload->'themes') IS DISTINCT FROM 'array' THEN
    RAISE EXCEPTION 'Payload must contain a "themes" array';
  END IF;

  FOR v_theme IN SELECT * FROM jsonb_array_elements(p_payload->'themes') LOOP
    v_theme_idx := v_theme_idx + 1;
    v_theme_fr := NULLIF(btrim(v_theme->>'name_fr'), '');
    v_theme_en := COALESCE(NULLIF(btrim(v_theme->>'name_en'), ''), v_theme_fr);
    v_theme_label := COALESCE(v_theme_fr, '#' || v_theme_idx);
    v_key := NULLIF(btrim(v_theme->>'key'), '');
    v_category_id := NULLIF(v_theme->>'category_id', '')::bigint;

    IF v_category_id IS NOT NULL THEN
      PERFORM 1 FROM public.question_categories WHERE id = v_category_id;
      IF NOT FOUND THEN
        RAISE EXCEPTION 'Theme %: category % does not exist', v_theme_label, v_category_id;
      END IF;
    ELSE
      IF v_theme_fr IS NULL THEN
        RAISE EXCEPTION 'Theme #%: name_fr is required', v_theme_idx;
      END IF;

      IF v_key IS NOT NULL THEN
        SELECT c.id INTO v_category_id FROM public.question_categories c WHERE c.source_key = v_key;
      END IF;

      IF v_category_id IS NULL THEN
        SELECT t.question_category_id INTO v_category_id
        FROM public.question_category_translations t
        JOIN public.question_categories c ON c.id = t.question_category_id
        WHERE public.normalize_text(t.name) IN (public.normalize_text(v_theme_fr), public.normalize_text(v_theme_en))
          AND (v_key IS NULL OR c.source_key IS NULL)
        ORDER BY (t.locale = 'fr') DESC, c.id
        LIMIT 1;

        IF v_category_id IS NOT NULL AND v_key IS NOT NULL THEN
          UPDATE public.question_categories SET source_key = v_key, updated_at = now() WHERE id = v_category_id;
        END IF;
      END IF;

      IF v_category_id IS NULL THEN
        INSERT INTO public.question_categories (level, is_active, source_key)
        VALUES (
          COALESCE(
            NULLIF(v_theme->>'level', '')::integer,
            (SELECT COALESCE(max(level), 0) + 1 FROM public.question_categories)
          ),
          true,
          v_key
        )
        RETURNING id INTO v_category_id;

        INSERT INTO public.question_category_translations (question_category_id, locale, name)
        VALUES (v_category_id, 'fr', v_theme_fr), (v_category_id, 'en', v_theme_en);

        v_categories_created := v_categories_created + 1;
      END IF;
    END IF;

    v_q_idx := 0;
    FOR v_question IN SELECT * FROM jsonb_array_elements(COALESCE(v_theme->'questions', '[]'::jsonb)) LOOP
      v_q_idx := v_q_idx + 1;
      v_q_fr := NULLIF(btrim(v_question->>'name_fr'), '');
      v_q_en := COALESCE(NULLIF(btrim(v_question->>'name_en'), ''), v_q_fr);
      v_source_fr := COALESCE(btrim(v_question->>'source_text_fr'), '');
      v_options := COALESCE(v_question->'options', '[]'::jsonb);

      IF v_q_fr IS NULL THEN
        RAISE EXCEPTION 'Theme %, question #%: name_fr is required', v_theme_label, v_q_idx;
      END IF;

      IF jsonb_typeof(v_options) <> 'array' OR jsonb_array_length(v_options) < 2 THEN
        RAISE EXCEPTION 'Theme %, question #%: at least 2 options are required', v_theme_label, v_q_idx;
      END IF;

      IF EXISTS (
        SELECT 1 FROM jsonb_array_elements(v_options) o
        WHERE NULLIF(btrim(o->>'name_fr'), '') IS NULL
      ) THEN
        RAISE EXCEPTION 'Theme %, question #%: every option needs a name_fr', v_theme_label, v_q_idx;
      END IF;

      SELECT count(*) INTO v_correct
      FROM jsonb_array_elements(v_options) o
      WHERE COALESCE((o->>'is_correct')::boolean, false);

      IF v_correct <> 1 THEN
        RAISE EXCEPTION 'Theme %, question #%: exactly one correct option expected (found %)',
          v_theme_label, v_q_idx, v_correct;
      END IF;

      v_type_code := NULLIF(btrim(v_question->>'type'), '');
      IF v_type_code IS NULL THEN
        SELECT array_agg(public.normalize_text(o->>'name_fr') ORDER BY public.normalize_text(o->>'name_fr'))
        INTO v_labels
        FROM jsonb_array_elements(v_options) o;

        v_type_code := CASE
          WHEN v_labels IN (ARRAY['faux', 'vrai'], ARRAY['false', 'true']) THEN 'true_false'
          ELSE 'multiple_choice_single_answer'
        END;
      END IF;

      IF v_type_code NOT IN ('multiple_choice_single_answer', 'true_false') THEN
        RAISE EXCEPTION 'Theme %, question #%: unsupported type "%"', v_theme_label, v_q_idx, v_type_code;
      END IF;

      IF v_type_code = 'true_false' AND jsonb_array_length(v_options) <> 2 THEN
        RAISE EXCEPTION 'Theme %, question #%: a true_false question needs exactly 2 options', v_theme_label, v_q_idx;
      END IF;

      SELECT id INTO v_type_id FROM public.question_types WHERE code = v_type_code;
      IF v_type_id IS NULL THEN
        RAISE EXCEPTION 'Question type "%" is missing from question_types', v_type_code;
      END IF;

      PERFORM 1
      FROM public.questions q
      JOIN public.question_translations qt ON qt.question_id = q.id AND qt.locale = 'fr'
      WHERE q.question_category_id = v_category_id
        AND public.normalize_text(qt.name) = public.normalize_text(v_q_fr);

      IF FOUND THEN
        v_skipped := v_skipped + 1;
        CONTINUE;
      END IF;

      PERFORM public.insert_question_data(jsonb_build_object(
        'name_fr', v_q_fr,
        'name_en', v_q_en,
        'source_text_fr', v_source_fr,
        'source_text_en', COALESCE(NULLIF(btrim(v_question->>'source_text_en'), ''), v_source_fr),
        'is_active', true,
        'category_id', v_category_id,
        'type_id', v_type_id,
        'options', (
          SELECT jsonb_agg(
            jsonb_build_object(
              'name_fr', btrim(e.o->>'name_fr'),
              'name_en', COALESCE(NULLIF(btrim(e.o->>'name_en'), ''), btrim(e.o->>'name_fr')),
              'is_correct', COALESCE((e.o->>'is_correct')::boolean, false)
            )
            ORDER BY e.ord
          )
          FROM jsonb_array_elements(v_options) WITH ORDINALITY AS e(o, ord)
        )
      ));

      v_inserted := v_inserted + 1;
    END LOOP;
  END LOOP;

  RETURN jsonb_build_object(
    'categories_created', v_categories_created,
    'questions_inserted', v_inserted,
    'questions_skipped', v_skipped
  );
END;
$$;
